# -*- coding: utf-8 -*-
"""Copy_of_Project_(1)_Guessing_Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEBkHGH1xImdX1y0lc4zM1KGg-wrJbP4

**Fatma Alzahraa Alhabbash**

# Guessing Game Project Description

* **`First: You ask the user to set the game level:`**
  * *(1) Easy*:
    * Limits : [1 - 10]  
    * No. of trials : 3
  * *(2) Intermediate*:
    * Limits : [1 - 100]
    * No. of trials : 7
  * *(3) Hard* :  
    * Limits : [1 - 1000]
    * No. of trials : 15

* **`Second: set the game settings according to the game level:`**
  * set the `guess` to a number within the limits using `random` module
  * set the number of trials: `n_trials`

* **`Finally: Play the game:`**
  * Ask the user to guess the number:
    * If he guessed it successfully : `print('Congratulations, you achieved it in {user_trials} trial') `
    * if he failed:
      * user_trials < n_trials: till him (Increase) or (Decrease)
      * user_trials = n_trials: `print('You Lose!')`

## Project Description

* **`First: You ask the user to set the game level:`**
  * *(1) Easy*:
    * Limits : [1 - 10]  
    * No. of trials : 3
  * *(2) Intermediate*:
    * Limits : [1 - 100]
    * No. of trials : 7
  * *(3) Hard* :  
    * Limits : [1 - 1000]
    * No. of trials : 15

* **`Second: start the game according to the game level:`**
  * set the `guess` to a number within the limits using `random` module
  * set the number of trials: `n_trials`

* **`Finally: start the game:`**
  * Ask the user to guess the number:
    * If he guessed it successfully : `print('Congratulations, you achieved it in {user_trials} trial') `
    * if he failed:
      * user_trials < n_trials: give him another trial within
      * user_trials = n_trials: `print('You Lose!')`

# Template of Solution

## Show the game levels
"""

def show_levels():
  # write your code here
  print('Game Levels : \n(1) Easy: \n* Limits : [1 - 10]  \n* No. of trials : 3')
  print('(2) Intermediate: \n* Limits : [1 - 100] \n* No. of trials : 7')
  print('(3) Hard : \n* Limits : [1 - 1000] \n* No. of trials : 15')

"""## Ask the user for the game level"""

def game_level_choice():
  # write your code here
  game_level = input('Enter the game level :\n(1) Easy 	 (2) Intermediate 	 (3) Hard: ')
  while game_level not in ('1','2','3'):
    print('Invalid Choice! Please choose 1, 2, or 3')
    game_level = input('Enter the game level :\n(1) Easy 	 (2) Intermediate 	 (3) Hard: ')
  return game_level

"""## Set the game settings according to the game level:

"""

def set_game_settings(game_level):
  # write your code here
  if game_level == '1':
    limits = range(1,11)
    n_trials = 3

  elif game_level == '2':
    limits = range(1,101)
    n_trials = 7

  elif game_level == '3':
    limits = range(1,1001)
    n_trials = 15

  return limits, n_trials

"""## Start Playing

> Hint: to generate random number in some range:

`import random`

`num = random.randint(lower, upper)`

 or

 `num = random.choice(range(lower, upper))`
"""

import random
def start_play(limits, n_trials):
  # write your code here
  num = random.choice(limits)
  gussed_num = int(input('I have a hidden number, guess it : '))
  flag = False
  user_trials = 0

  for trial in range(n_trials): # عشان ما نكتب جملة الادخال من اليوزر أكتر من مرة while loop الأفضل نستخدم
    user_trials += 1
    if gussed_num == num:
      flag = True
      break
    else:
      if gussed_num not in limits:
        print('The gussed number was out of range! Please guess another number')
        gussed_num = int(input('I have a hidden number, guess it : '))
      elif gussed_num > num:
        print('No, Decrease!')
        gussed_num = int(input('I have a hidden number, guess it : '))
      elif gussed_num < num:
        print('No, Increase!')
        gussed_num = int(input('I have a hidden number, guess it : '))

  if flag:
    print(f'Congratulations, you achieved it in {user_trials} trials')
  else:
    print(f'You Lose! The number is {num}')

"""# Play Again ?"""

def play_again():
  play_again = input("Play again ? [0] No, [1] Yes: ")
  while play_again != '0' and play_again != '1':
    print('Invalid Choice! Please choose 0 or 1')
    play_again = input("Play again ? [0] No, [1] Yes: ")
  return int(play_again)

"""## Let's Play"""

def play():
  while True:
    show_levels()
    game_level = game_level_choice()
    limits, n_trials = set_game_settings(game_level)
    start_play(limits, n_trials)
    if not play_again():
      break

play()